### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by sklages** [sequencing/NxTrim#14]
Hi,

as this is still an alpha version, I wonder if this tool is still under "active development"?
Will this tool be "official" part of https://github.com/Illumina ? 
best,
Sven

**Comment by jaredo** [comment]
Hi Sven,

I guess I can remove the "alpha" on the next release.  Certainly the tool will continue to be actively supported.  In terms of further development, my only plans are to remove BOOST dependencies since they cause issues for many people when compiling. I am happy to take feature requests though!

We will move it to https://github.com/Illumina at some point.

cheers,

Jared

**Comment by sklages** [comment]
Hi Jared,
cool, .. I'd like to use it routinely on (illumina) fastq data. Currently I use TGAC's NextClip for adaptor removal. 

Usually we remove duplicates from LMP data. To just avoid another I/O-read/write cycle in data preprocessing, it would be good to have an option for that. Maybe with a accompanying parameter for "stringency" when searching for duplicates.

best,
Sven

**Comment by jaredo** [comment]
Duplicate removal is probably beyond the scope of the tool. I'd be unlikely to be able to implement something as good as what is currently available. 

Note that you can already pipe nxtrim to stdout and straight to an aligner to avoid unnecessary I/O:
```
nxtrim  -1 EcMG1_R1.fastq.gz -2 EcMG1_R2.fastq.gz --justmp --stdout | bwa mem -p EcMG.fna - > EcMG.mp.bam
```
I guess you could do the same thing with a duplicate removal tool?  I'm not sure what the state-of-the-art is on reference free duplicate detection.

**Comment by sklages** [comment]
Well, there are a handful of tools ... few of them accepting interleaved as input. It should be possible though to pipe or to use bash's comand substitution.

best,
Sven
