### ISSUE TITLE
How to pipe the outputs of trimming onto Galaxy server BWA?

### ISSUE THREAD

**Issue by odoland** [sequencing/NxTrim#25]
I want to send both trimmed unknown and MP reads into one fastq file, 

MPandunknown.R1.fastq and MPandunknown.R2.fastq, for alignment with BWA-MEM on Galaxy servers. How can I do this?

Thanks!

**Comment by jaredo** [comment]
```
nxtrim --stdout -1 EcMG1_ATGTCA_L001_R1_001.fastq.gz -2 EcMG1_ATGTCA_L001_R2_001.fastq.gz | bwa mem EcMG.fna -p - > out.sam
```

**Comment by odoland** [comment]
Thanks, Jaredo, but my computer can't handle BWA-MEM. Is there away from me to send these outputs directly to upload to https://usegalaxy.org/? 

Sorry, I am new to this. Thanks for your help!

**Comment by jaredo** [comment]
I don't know much/anything about galaxy. If you just want to generate trimmed fastq files run:

```
nxtrim --stdout -1 EcMG1_ATGTCA_L001_R1_001.fastq.gz -2 EcMG1_ATGTCA_L001_R2_001.fastq.gz | gzip -c > EcMG1_trimmed.fastq.gz
```

**Comment by jvollme** [comment]
If i understand you correctly, you just want the output for MP and unknown combined in a single file, yes?
Well in that case, it is as simple as just concatenating the respective files after NXtrim is done, because the fastq-format is actually a relatively simple text format. So you could just copy the input of trimmed_R1.mp.fastq and the input of trimmed_R1.unkown.fastq into a single file "trimmed_R1_MPandUNKNOWN.fastq" (and then do the same for the respective "_R2."-files.
You just have to make sure that you always copy them in the same order (because the order of the reads in the file is how most programs identify which forward and reverse read belong together).

In Linux/unix/Mac this would be as simple as using these two commands :
`cat trimmed_R1.mp.fastq trimmed_R1.unknown.fastq > trimmed_R1.MPandUNKNOWN.fastq"`
and
`cat trimmed_R2.mp.fastq trimmed_R2.unknown.fastq > trimmed_R2.MPandUNKNOWN.fastq`

If your trimmed fastq-files are compressed, you can just substitute "cat" for "zcat" in the above command:
`zcat trimmed_R1.mp.fastq.gz trimmed_R1.unknown.fastq.gz > trimmed_R1.MPandUNKNOWN.fastq`
and
'zcat trimmed_R2.mp.fastq.gz trimmed_R2.unknown.fastq.gz > trimmed_R2.MPandUNKNOWN.fastq`

on windows i think you can use "type" as an equivalent to cat (I mostly don't work under windows myself). You'd have to go into the command-shell (not much use trying to open large fastq-files with a GUI-based editor) and type:
`type trimmed_R1.mp.fastq trimmed_R1.unknown.fastq > trimmed_R1.MPandUNKNOWN.fastq"`
and 
`type trimmed_R2.mp.fastq trimmed_R2.unknown.fastq > trimmed_R2.MPandUNKNOWN.fastq`

**Comment by jaredo** [comment]
Note that `--stdout` will now print both MP/unknown to stdout, so there is no longer a need for the separate concatenation stp.
